#!/usr/bin/env bash
# A script to transfer a file to a server
# - Accepts 4 parameters
#     - The path to the file to be transferred
#     - The IP of the server to transfer to
#     - The username scp connects with
#     - The path to the SSH private key that scp uses
# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# - scp must transfer the file to the user home directory ~/
# - Strict host key checking must be disabled when using scp

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

if [ $# -eq 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
