#!/usr/bin/env bash
# A script to install nginx on a server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page) using curl,
#     it must return a page that contains the string `Hello World!`
# - Configure Nginx so that its redirecting to another page permanently

# Install nginx
apt-get -y update
apt-get -y install nginx

# Start nginx
if [[ ! $(pgrep nginx) ]]; then
    service nginx start
fi

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Get the first root directory of nginx from the configuration file
root_dir=$(grep "root" /etc/nginx/sites-available/default | cut -d " " -f 2 | tr -d ";" | head -1)

# Create the directory if it doesn't exist
if [[ ! -d $root_dir ]]; then
    sudo mkdir -p "$root_dir"
fi

# Write `Hello World!` to the index.html file
echo "Hello World!" > "$root_dir"/index.html

# Check if Nginx is running and serving the expected content
response=$(curl -s http://localhost)
if [[ $response == "Hello World!" ]]; then
  echo "Nginx installation and configuration successful!"
else
  echo "Nginx installation or configuration failed."
  exit 1
fi

# Configure Nginx to redirect to another page permanently with a 301 Moved Permanently HTTP response
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://linkedin.com/in/achrafelkhnissi/ permanent;" /etc/nginx/sites-available/default

# Check if the configuration is valid
if nginx -t | grep "successful"; then
  echo "Nginx configuration failed."
  exit 1
fi

# Reload Nginx
nginx -s reload

# Restart Nginx
service nginx restart

# Check if Nginx is redirecting to the expected page

exit 0
